BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Planet] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] VARCHAR(255) NOT NULL,
    [description] NVARCHAR(1000),
    [diameter] INT NOT NULL,
    [moons] INT NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Planet_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Planet_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
