export * from './main/main.component'
export * from './nav/nav.component'
export * from './new/new.component'
export * from './product/product.component'
export * from './about/about.component'
export * from './shop/shop.component'
export * from './apple/apple.component'
export * from './contact/contact.component'
